language: erlang

env:
   - ST=Pharo-1.4
   - ST=Pharo-2.0
   - ST=PharoCore-1.3
   - ST=Squeak4.3
   - ST=GemStone-2.4.4.1
   - ST=GemStone-2.4.4.7
   - ST=GemStone-2.4.5
   - ST=GemStone-2.4.5.1
   - ST=GemStone-3.0.1
   - ST=GemStone-3.1.0.2

# blacklist
branches:
  except:
    - master

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $BUILDER_CI_HOME/testTravisCI.sh

