language: erlang

# build matrix: "PharoCore-1.3" or "Squeak4.3" ... parallel tests for
#   all listed environments
env:
   - ST=PharoCore-1.3

install:
   - git clone git://github.com/dalehenrich/buildCI.git
   - cd buildCI
   - ./build_install.sh -c

script:
   - ./build.sh -i PharoCore-1.3 -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - if ( test -e PharoDebug.log ); then cat PharoDebug.log; fi
   - if ( test -e PharoDebug.log ); then die; fi
   - if ( test -e TravisCIResults.txt ); then cat TravisCIResults.txt; fi
   - echo "DONE...."
