language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
   - GemStone-2.4.8
   - GemStone-3.1.0.6
   - GemStone-3.2.17
   - GemStone-3.3.9
   - GemStone-3.4.5
   - GemStone-3.5.3

matrix:
   allow_failures:
     - smalltalk: GemStone-2.4.8 #not sure it is worth the effort to clean up 2.4.x problems

cache:
  directories:
    - $SMALLTALK_CI_CACHE

notifications:
  slack: gemtalksystems:4YWbzy6sJN9cE0FhxvUPP8nS
